#!/usr/bin/env node
/**
 * Writes public/sitemap.xml from the live catalogue.
 *
 *   node scripts/build-sitemap.mjs --site https://www.prathibalanka.com
 *   node scripts/build-sitemap.mjs --site https://<frontend>.up.railway.app --dry-run
 *
 * Why it reads the site rather than a list in this repository: the journeys and posts are rows in a
 * database that the agency edits from the console, so a sitemap written by hand here would be stale
 * the first time somebody adds a trip. The API is public for exactly these two endpoints, so no
 * credentials are needed.
 *
 * Run it after adding journeys or posts, then rebuild and redeploy the front end - the file is served
 * as a static asset, so it only exists once the image carrying it does.
 */
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { parseArgs } from 'node:util'

const { values: options } = parseArgs({
  options: {
    site: { type: 'string' },
    'dry-run': { type: 'boolean', default: false },
  },
})

const site = (options.site ?? 'https://www.prathibalanka.com').replace(/\/+$/, '')
const dryRun = options['dry-run'] === true

/** The static pages, with the same relative weights the hand-written file used. */
const STATIC_PAGES = [
  ['/', 'weekly', '1.0'],
  ['/journeys', 'weekly', '0.9'],
  ['/plan', 'monthly', '0.8'],
  ['/journal', 'weekly', '0.7'],
  ['/about', 'monthly', '0.7'],
  ['/contact', 'monthly', '0.6'],
  ['/gallery', 'monthly', '0.6'],
  ['/reviews', 'monthly', '0.5'],
]

async function get(path) {
  try {
    const response = await fetch(`${site}${path}`)
    if (!response.ok) {
      console.warn(`  ! ${path} answered ${response.status}; skipping those entries`)
      return []
    }
    const body = await response.json()
    return Array.isArray(body) ? body : []
  } catch (error) {
    console.warn(`  ! ${path} could not be read (${error.message}); skipping those entries`)
    return []
  }
}

function url(loc, changefreq, priority, lastmod) {
  return [
    '  <url>',
    `    <loc>${site}${loc}</loc>`,
    ...(lastmod ? [`    <lastmod>${String(lastmod).slice(0, 10)}</lastmod>`] : []),
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n')
}

const packages = await get('/api/packages')
const posts = await get('/api/journal/published')
console.log(`  ${packages.length} journeys, ${posts.length} published posts`)

const entries = [
  ...STATIC_PAGES.map(([path, freq, priority]) => url(path, freq, priority)),
  ...packages.map((pkg) => url(`/journeys/${pkg.packageId}`, 'monthly', '0.8', pkg.updatedAt)),
  ...posts.map((post) => url(`/journal/${post.journalId}`, 'monthly', '0.6', post.updatedAt ?? post.publishedAt)),
]

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.mjs from the live catalogue. Edits here are overwritten. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join('\n')}
</urlset>
`

if (dryRun) {
  console.log(xml)
  console.log('Dry run: nothing written.')
  process.exit(0)
}

const target = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'sitemap.xml')
await writeFile(target, xml, 'utf8')
console.log(`  wrote ${entries.length} URLs to public/sitemap.xml`)
console.log('  rebuild and redeploy the front end for it to be served.')
